server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /$\{segment}

        - id: patient-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/patients/**
          filters:
            - RewritePath=/api/patients/(?<segment>.*), /$\{segment}

        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<segment>.*), /$\{segment}

jwt:
  secret: your_super_secret_jwt_key_that_is_very_long_and_secure
